---
abstract: 'Construct command line and perl clients for RESTful services.'
author:
  - 'Graham Ollis <plicease@cpan.org>'
build_requires:
  Log::Log4perl::CommandLine: 0
  Module::Build: 0.3601
  Test::More: 0
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300021, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Clustericious-Client
no_index:
  directory:
    - share
    - example
recommends:
  EV: 0
requires:
  Clustericious::Config: 0.01
  Clustericious::Log: 0
  Data::Rmap: 0
  Date::Parse: 0
  DateTime: 0
  DateTime::Format::DateParse: 0
  DateTime::Format::ISO8601: 0
  JSON::XS: 0
  Log::Log4perl: 0
  Log::Log4perl::CommandLine: 0
  MojoX::Log::Log4perl: 0
  Mojolicious: 1.65
  Term::Prompt: 0
  YAML::XS: 0
resources:
  bugtracker: https://github.com/plicease/clustericious-client/issues
  homepage: http://perl.wdlabs.com/Clustericious-Client/
  repository: git://github.com/plicease/clustericious-client.git
version: 0.85
